### ISSUE TITLE
Error after a While

### ISSUE THREAD

**Issue by NeutronX-dev** [sitesgithub/dncc#2]
After It runs for a while I get this error :
```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
How may I fix it?

**Comment by sitesgithub** [comment]
Rerun the app again, this happens if the proxies are bad or your computer loses connection.
