### ISSUE TITLE
I keep getting an unhandled error

### ISSUE THREAD

**Issue by Pool800** [sitesgithub/dncc#3]
Hi,
I need to get this working as soon as possible but everytime it seems to get a hit, instead it has an error message. The error goes like the follwing below:

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by BlaNKtext** [comment]
https://github.com/BlaNKtext/Discord-Nitro-code-gen-checker
use this one i fixed his code

**Comment by sitesgithub** [comment]
i don't care this is dead
